lc_map:
 京东: jd
 百世快运: baishiwuliu
 EMS经济: eyb
 中通快运: zhongtongkuaiyun
 韵达快运: ydky

 百世: huitongkuaidi
 ems: ems
 邮政: youzhengguonei
 中通: zhongtong
 韵达: yunda
 申通: shentong
 圆通: yuantong
 极兔: jito
 壹米滴答: yimidida
 中铁快运: zhongtiekuaiyun
 安能物流: annengwuliu
login:
 username: 江苏森虎
 userpwd: 888888


